"""add email to complaint model

Revision ID: 8f01cb3b52b4
Revises: 86e550dc70d1
Create Date: 2025-06-27 11:39:57.558370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f01cb3b52b4'
down_revision: Union[str, Sequence[str], None] = '86e550dc70d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'email')
    # ### end Alembic commands ###
